name: Build Pull Request

on: pull_request

jobs:
  test_job:
   name: Test
   runs-on: ubuntu-latest   
   steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Restore Cache
      uses: actions@v2
        with:
          path:|
            ~/.gradle/caches
            ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{hashFiles('**/.*gradle*')}}
        restore-keys: | 
          ${{ runner.os }}-gradle-
          
    - name: Run Debug Tests
      run: ./gradlew testDebugUnitTest       
      
    - name: Upload Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with: 
        name: test-reports
        path: '**/build/reports/tests/'
        
  lint_job:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Restore Cache
      uses: actions@v2
        with:
          path:|
            ~/.gradle/caches
            ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{hashFiles('**/.*gradle*')}}
        restore-keys: | 
          ${{ runner.os }}-gradle-
                
    - name: Run Debug ktlint
      run: ./gradlew ktlintDebugCheck
      
    - name: Run Debug Lint
      run: ./gradlew lintDebug
      
      
  assemble_job:
    name: Assemble
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Restore Cache
      uses: actions@v2
        with:
          path:|
            ~/.gradle/caches
            ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{hashFiles('**/.*gradle*')}}
        restore-keys: | 
          ${{ runner.os }}-gradle-
          
    - name: Assemble Debug
      run: ./gradlew assembleDebug
  
#   notification_job:
#     needs: [test_job, lint_job, assemble_job]
#     name: Notify Build Status
